name: New feature
description: Suggest or request a new feature
title: "[2.0.0] - "
labels: ["type:feature"]
projects:
  - "[2.0.0] - HappyTree"
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to properly describe the new feature you are suggesting.
  - type: textarea
    id: nf_description
    attributes:
      label: Describe the feature
      placeholder: A new method in the interface to convert nodes into JSON...
    validations:
      required: true
  - type: textarea
    id: nf_rationale
    attributes:
      label: It should be implemented because
      placeholder: It will free the API client from the responsibility of...
    validations:
      required: true
  - type: textarea
    id: nf_context
    attributes:
      label: Additional context
      placeholder: |
        Add any other context or screenshots about the feature request here.
  - type: checkboxes
    id: nf_assign_me
    attributes:
      label: "Extra fields"
      options:
        - label: "I want to work on this issue"
          required: false
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion! Let's see together if it can be implemented.
