package com.madzera.happytree.session;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

import com.madzera.happytree.Element;
import com.madzera.happytree.TreeManager;
import com.madzera.happytree.TreeSession;
import com.madzera.happytree.TreeTransaction;
import com.madzera.happytree.core.HappyTree;
import com.madzera.happytree.demo.model.Directory;
import com.madzera.happytree.exception.TreeException;

/**
 * 
 * Test class for {@link TreeSession} operations.
 * 
 * @author Diego Madson de Andrade Nóbrega
 *
 */
public class TreeSessionTest {

	/**
	 * Test for the {@link TreeSession#getSessionId()}.
	 * 
	 * <p><b>Test:</b></p>
	 * Get the session identifier.
	 * <p><b>Expected:</b></p>
	 * Match the session identifier at the creation with the return of
	 * {@link TreeSession#getSessionId()}.
	 * <p><b>Steps:</b></p>
	 * <ol>
	 * 	<li>Get the transaction;</li>
	 * 	<li>Initialize a session with a specific identifier;</li>
	 * 	<li>Get the current session;</li>
	 * 	<li>Compare the result of {@link TreeSession#getSessionId()} with the
	 * 	previous identifier.</li>
	 * </ol>
	 * 
	 * @throws TreeException in case of an error
	 */
	@Test
	public void getSessionId() throws TreeException {
		final String sessionId = "FIRST_SESSION";
		
		TreeManager manager = HappyTree.createTreeManager();
		TreeTransaction transaction = manager.getTransaction();
		
		transaction.initializeSession(sessionId, Directory.class);
		TreeSession session = transaction.currentSession();
		
		assertEquals(sessionId, session.getSessionId());
	}
	
	/**
	 * Test for the {@link TreeSession#isActive()}.
	 * 
	 * <p><b>Test:</b></p>
	 * Verify the status session.
	 * <p><b>Expected:</b></p>
	 * Initialize a session and verify if it is active. After that deactivate
	 * the session and verify if it changed to not active.
	 * <p><b>Steps:</b></p>
	 * <ol>
	 * 	<li>Get the transaction;</li>
	 * 	<li>Initialize a session;</li>
	 * 	<li>Get the current session;</li>
	 * 	<li>Verify if the session is active;</li>
	 * 	<li>Deactivate the same session by invoking
	 * 	{@link TreeTransaction#deactivateSession()};</li>
	 * 	<li>Verify if the same session is not active anymore.</li>
	 * </ol>
	 * 
	 * @throws TreeException in case of an error
	 */
	@Test
	public void isActive() throws TreeException {
		final String sessionId = "SESSION_STATUS";
		
		TreeManager manager = HappyTree.createTreeManager();
		TreeTransaction transaction = manager.getTransaction();
		
		transaction.initializeSession(sessionId, Directory.class);
		TreeSession session = transaction.currentSession();
		assertTrue(session.isActive());
		
		transaction.deactivateSession();
		session = transaction.currentSession();
		assertFalse(session.isActive());
	}
	
	/**
	 * Test for the {@link TreeSession#tree()}.
	 * 
	 * <p><b>Test:</b></p>
	 * Get the root element.
	 * <p><b>Expected:</b></p>
	 * A not <code>null</code> root element with the default <i>id</i> called
	 * <i>HAPPYTREE_ROOT</i>.
	 * <p><b>Steps:</b></p>
	 * <ol>
	 * 	<li>Get the transaction;</li>
	 * 	<li>Initialize a session;</li>
	 * 	<li>Get the current session;</li>
	 * 	<li>Get the root element by invoking {@link TreeSession#tree()};</li>
	 * 	<li>Verify if the root element is not <code>null</code>;</li>
	 * 	<li>Verify if the root element has id called &quot;HAPPYTREE_ROOT&quot;.
	 * 	</li>
	 * </ol>
	 * 
	 * @throws TreeException in case of an error
	 */
	@Test
	public void tree() throws TreeException {
		final String sessionId = "TREE";
		final String rootId = sessionId;
		
		TreeManager manager = HappyTree.createTreeManager();
		TreeTransaction transaction = manager.getTransaction();
		
		transaction.initializeSession(sessionId, Directory.class);
		TreeSession session = transaction.currentSession();
		Element<Directory> root = session.tree();
		
		assertNotNull(root);
		assertEquals(rootId, root.getId());
	}

	/**
	 * Test for the {@link TreeSession#hashcode()}.
	 * 
	 * <p><b>Test:</b></p>
	 * Generate and compare session hashcode.
	 * <p><b>Expected:</b></p>
	 * The same hashcode generated by the session identifier <i>HASH_CODE</i>.
	 * <p><b>Steps:</b></p>
	 * <ol>
	 * 	<li>Get the transaction;</li>
	 * 	<li>Initialize a session wih the identifier called <i>HASH_CODE</i>;</li>
	 * 	<li>Get the current <code>session1</code>;</li>
	 * 	<li>Initialize a session wih the identifier called <i>HASH_CODE_</i>;
	 * 	</li>
	 * 	<li>Get, again, the previous session and reassign to a new variable
	 * 	called <code>session2</code>;</li>
	 * 	<li>Compare the hashcodes from the <code>session1</code> and
	 * 	<code>session2.</code></li>
	 * 	</li>
	 * </ol>
	 * 
	 * @throws TreeException in case of an error
	 */
	@Test
	public void sessionHashCode() throws TreeException {
		final String sessionId1 = "HASH_CODE";
		final String sessionId2 = "HASH_CODE_2";
		
		TreeManager manager = HappyTree.createTreeManager();
		TreeTransaction transaction = manager.getTransaction();
		
		transaction.initializeSession(sessionId1, Directory.class);
		TreeSession session1 = transaction.currentSession();
		transaction.initializeSession(sessionId2, Directory.class);
		TreeSession session2 = transaction.sessionCheckout(sessionId1);

		assertEquals(session1.hashCode(), session2.hashCode());
	}
}
