package com.madzera.happytree.session;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

import com.madzera.happytree.Element;
import com.madzera.happytree.TreeManager;
import com.madzera.happytree.TreeSession;
import com.madzera.happytree.TreeTransaction;
import com.madzera.happytree.core.HappyTree;
import com.madzera.happytree.demo.model.Directory;
import com.madzera.happytree.exception.TreeException;

/**
 * 
 * Test class for {@link TreeSession} operations.
 * 
 * @author Diego Madson de Andrade Nóbrega
 *
 */
public class TreeSessionTest {

	/**
	 * Test for the {@link TreeSession#getSessionId()}.
	 * 
	 * <p><b>Test:</b></p>
	 * Get the session identifier.
	 * <p><b>Expected:</b></p>
	 * Match the session identifier at the creation with the return of
	 * {@link TreeSession#getSessionId()}.
	 * <p><b>Steps:</b></p>
	 * <ol>
	 * 	<li>Get the transaction;</li>
	 * 	<li>Initialize a session with a specific identifier;</li>
	 * 	<li>Get the current session;</li>
	 * 	<li>Compare the result of {@link TreeSession#getSessionId()} with the
	 * 	previous identifier.</li>
	 * </ol>
	 * 
	 * @throws TreeException in case of an error
	 */
	@Test
	public void getSessionId() throws TreeException {
		final String sessionId = "FIRST_SESSION";
		
		TreeManager manager = HappyTree.createTreeManager();
		TreeTransaction transaction = manager.getTransaction();
		
		transaction.initializeSession(sessionId, Directory.class);
		TreeSession session = transaction.currentSession();
		
		assertEquals(sessionId, session.getSessionId());
	}
	
	/**
	 * Test for the {@link TreeSession#isActive()}.
	 * 
	 * <p><b>Test:</b></p>
	 * Verify the status session.
	 * <p><b>Expected:</b></p>
	 * Initialize a session and verify if it is active. After that deactivate
	 * the session and verify if it changed to not active.
	 * <p><b>Steps:</b></p>
	 * <ol>
	 * 	<li>Get the transaction;</li>
	 * 	<li>Initialize a session;</li>
	 * 	<li>Get the current session;</li>
	 * 	<li>Verify if the session is active;</li>
	 * 	<li>Deactivate the same session by invoking
	 * 	{@link TreeTransaction#deactivateSession()};</li>
	 * 	<li>Verify if the same session is not active anymore.</li>
	 * </ol>
	 * 
	 * @throws TreeException in case of an error
	 */
	@Test
	public void isActive() throws TreeException {
		final String sessionId = "SESSION_STATUS";
		
		TreeManager manager = HappyTree.createTreeManager();
		TreeTransaction transaction = manager.getTransaction();
		
		transaction.initializeSession(sessionId, Directory.class);
		TreeSession session = transaction.currentSession();
		assertTrue(session.isActive());
		
		transaction.deactivateSession();
		session = transaction.currentSession();
		assertFalse(session.isActive());
	}
	
	/**
	 * Test for the {@link TreeSession#tree()}.
	 * 
	 * <p><b>Test:</b></p>
	 * Get the root element.
	 * <p><b>Expected:</b></p>
	 * A not <code>null</code> root element with the default <i>id</i> called
	 * <i>HAPPYTREE_ROOT</i>.
	 * <p><b>Steps:</b></p>
	 * <ol>
	 * 	<li>Get the transaction;</li>
	 * 	<li>Initialize a session;</li>
	 * 	<li>Get the current session;</li>
	 * 	<li>Get the root element by invoking {@link TreeSession#tree()};</li>
	 * 	<li>Verify if the root element is not <code>null</code>;</li>
	 * 	<li>Verify if the root element has id called &quot;HAPPYTREE_ROOT&quot;.
	 * 	</li>
	 * </ol>
	 * 
	 * @throws TreeException in case of an error
	 */
	@Test
	public void tree() throws TreeException {
		final String sessionId = "TREE";
		final String rootId = sessionId;
		
		TreeManager manager = HappyTree.createTreeManager();
		TreeTransaction transaction = manager.getTransaction();
		
		transaction.initializeSession(sessionId, Directory.class);
		TreeSession session = transaction.currentSession();
		Element<Directory> root = session.tree();
		
		assertNotNull(root);
		assertEquals(rootId, root.getId());
	}

	/**
	 * Test for the {@link Object#hashCode()} local implementation.
	 * 
	 * <p><b>Test:</b></p>
	 * Generate and compare session hash code.
	 * <p><b>Expected:</b></p>
	 * The same hash code generated by the session identifier <i>HASH_CODE_1</i>.
	 * <p><b>Steps:</b></p>
	 * <ol>
	 * 	<li>Get the transaction;</li>
	 * 	<li>Initialize a first session with the identifier called
	 * 	<i>sessionHashCode1</i>;</li>
	 * 	<li>Get the first session and assign to <code>session1</code> variable;
	 * 	</li>
	 * 	<li>Initialize a second session with the identifier called
	 * 	<i>sessionHashCode2</i>;</li>
	 * 	<li>Get, again, the first session and reassign to a new variable called
	 * 	<code>session2</code>;</li>
	 * 	<li>Compare the hash codes from the <code>session1</code> and
	 * 	<code>session2</code> variables - should be <code>true</code>.</li>
	 * 	</li>
	 * </ol>
	 * 
	 * @throws TreeException in case of an error
	 */
	@Test
	public void sessionHashCode() throws TreeException {
		final String sessionId1 = "sessionHashCode1";
		final String sessionId2 = "sessionHashCode2";

		TreeManager manager = HappyTree.createTreeManager();
		TreeTransaction transaction = manager.getTransaction();
		
		transaction.initializeSession(sessionId1, Directory.class);
		TreeSession session1 = transaction.currentSession();
		transaction.initializeSession(sessionId2, Directory.class);
		TreeSession session2 = transaction.sessionCheckout(sessionId1);

		assertEquals(session1.hashCode(), session2.hashCode());
	}

	/**
	 * Test for the {@link Object#equals(Object)} local implementation.
	 * 
	 * <p><b>Test:</b></p>
	 * Compare equality between 3 session objects.
	 * <p><b>Expected:</b></p>
	 * A <code>true</code> result when two sessions share the same object or the
	 * same session identifier and <code>false</code> when one of these session
	 * is <code>null</code>, also one of these objects has different class or
	 * different identifier.
	 * <p><b>Steps:</b></p>
	 * <ol>
	 * 	<li>Get the transaction;</li>
	 * 	<li>Initialize a first session with the identifier called
	 * 	<i>sessionEquals1</i>;</li>
	 * 	<li>Get the first session and assign to the <code>session1</code>
	 * 	variable;</li>
	 * 	<li>Initialize a second session with the identifier called
	 * 	<i>sessionEquals2</i>;</li>
	 * 	<li>Get a second session and assign to the <code>session2</code>
	 * 	variable;</li>
	 * 	<li>Destroy all sessions;</li>
	 * 	<li>Initialize a third session with the same identifier as
	 * 	<code>session1</code> variable;</li>
	 * 	<li>Compare the session1 with itself - should be <code>true</code>;</li>
	 * 	<li>Compare the session1 with null - should be <code>false</code>;</li>
	 * 	<li>Compare the session1 with session2 - should be <code>false</code>;
	 * 	</li>
	 * 	<li>Compare the session1 with session3 - should be <code>true</code>.
	 * 	</li>
	 * </ol>
	 * 
	 * @throws TreeException in case of an error
	 */
	@Test
	public void sessionEquals() throws TreeException {
		final String sessionId1 = "sessionEquals1";
		final String sessionId2 = "sessionEquals2";
		
		TreeManager manager = HappyTree.createTreeManager();
		TreeTransaction transaction = manager.getTransaction();
		
		transaction.initializeSession(sessionId1, Directory.class);
		TreeSession session1 = transaction.currentSession();
		transaction.initializeSession(sessionId2, Directory.class);
		TreeSession session2 = transaction.currentSession();

		transaction.destroyAllSessions();

		transaction.initializeSession(sessionId1, Directory.class);
		TreeSession session3 = transaction.currentSession();

		assertEquals(session1, session1);
		assertNotEquals(session1, null);
		assertNotEquals(session1, Directory.class);
		assertNotEquals(session1, session2);
		assertEquals(session1, session3);
	}

	/**
	 * Test for the {@link Object#toString()} local implementation.
	 * 
	 * <p><b>Test:</b></p>
	 * Compare the <code>toString()</code> result from a initialized session.
	 * <p><b>Expected:</b></p>
	 * A <code>true</code> result between a <code>toString()</code> comparison
	 * from a initialized session and the
	 * &quot;TreeSessionCore [identifier=sessionToString]&quot; value.
	 * <p><b>Steps:</b></p>
	 * <ol>
	 * 	<li>Declare a constant with a expected result value;</li>
	 * 	<li>Get the transaction;</li>
	 * 	<li>Initialize a session with the identifier called
	 * 	<i>sessionToString</i>;</li>
	 * 	<li>Get the session and assign to <code>session</code> variable;</li>
	 * 	<li>Compare the <code>session.toString()</code> with the
	 * 	<code>expectedResult</code> value - should be <code>true</code>.</li>
	 * 	</li>
	 * </ol>
	 * 
	 * @throws TreeException in case of an error
	 */
	@Test
	public void sessionToString() throws TreeException {
		final String sessionId = "sessionToString";
		final String expectedResult =
			"TreeSessionCore [identifier=" + sessionId + "]";
		
		TreeManager manager = HappyTree.createTreeManager();
		TreeTransaction transaction = manager.getTransaction();
		transaction.initializeSession(sessionId, Directory.class);
		TreeSession session = transaction.currentSession();

		assertEquals(expectedResult, session.toString());
	}
}
